// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyXvd80dfsCxwtbS5uxxWn8YhxwkHB9A',
    appId: '1:895022821760:web:e81d14a8b751f16325d165',
    messagingSenderId: '895022821760',
    projectId: 'd1plom',
    authDomain: 'd1plom.firebaseapp.com',
    storageBucket: 'd1plom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcFQqJxUN-Cz725PchgEUkifjAjliPwzc',
    appId: '1:895022821760:android:15b214519ef446e125d165',
    messagingSenderId: '895022821760',
    projectId: 'd1plom',
    storageBucket: 'd1plom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWPEIwyTyvAONBLkei6GNkcdMIQX9wsD8',
    appId: '1:895022821760:ios:9469a427012fd2e325d165',
    messagingSenderId: '895022821760',
    projectId: 'd1plom',
    storageBucket: 'd1plom.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWPEIwyTyvAONBLkei6GNkcdMIQX9wsD8',
    appId: '1:895022821760:ios:9469a427012fd2e325d165',
    messagingSenderId: '895022821760',
    projectId: 'd1plom',
    storageBucket: 'd1plom.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLyXvd80dfsCxwtbS5uxxWn8YhxwkHB9A',
    appId: '1:895022821760:web:1d31dc1416297bf025d165',
    messagingSenderId: '895022821760',
    projectId: 'd1plom',
    authDomain: 'd1plom.firebaseapp.com',
    storageBucket: 'd1plom.firebasestorage.app',
  );
}
